language: generic

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-4.9 CC=gcc-4.9 COMMON_OS_NAME=${TRAVIS_OS_NAME}
      addons:
        apt:
          packages:
            - g++-4.9
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test    
    # - os: linux
    #   env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8 COMMON_OS_NAME=${TRAVIS_OS_NAME}
    #   addons:
    #     apt:
    #       packages:
    #         - clang-3.8
    #       sources: *sources
    # - os: osx
    #   osx_image: xcode8
    #   env: CC=gcc-4.9 && CXX=g++-4.9 COMMON_OS_NAME=darwin
    # - os: osx
    #   osx_image: xcode8
    #   env: CC=clang && CXX=clang++ COMMON_OS_NAME=darwin

before_install:
  - echo $LANG
  - echo $LC_ALL
  - $CXX --version

script:
  #    - rvm get head  # Workaround 'shell_session_update: command not found'
  - set -e
  # - make test
  # - python setup.py build
  # - python setup.py test
  # Test CMake build scripts.
  - export VERBOSE=1
  - cmake . -Bbuild && cmake --build build --target run_tests
  # make a tarfile for the binaries and rename for os and tag
  # - make dist
  # - mv jsonnet-bin.tar.gz jsonnet-bin-${TRAVIS_TAG}-${COMMON_OS_NAME}.tar.gz
